: ODD ( a -- b ) 2 MOD 1 = ;
: POW2-REC ( a b -- c d | c ) DUP ODD IF DROP ELSE SWAP 1 + SWAP 2 / RECURSE THEN ;
: POW2 ( a -- b ) 0 SWAP POW2-REC ;

: SINGLE-DIGIT ( a -- -1/0 ) 10 < ;
: ACCUMULATE DUP 10 MOD ROT + SWAP 10 / ;
: TVERRSUM-REC ( acc rem -- acc+ rem- | acc ) DUP SINGLE-DIGIT IF + ELSE ACCUMULATE RECURSE THEN ;
: TVERRSUM ( rem -- acc ) 0 SWAP TVERRSUM-REC DUP SINGLE-DIGIT IF ELSE RECURSE THEN ;

: TVERRSUM-RECP ( acc rem -- acc+ rem- | acc ) DUP SINGLE-DIGIT IF + ELSE ACCUMULATE 2DUP SWAP . . CR RECURSE THEN ;
: TVERRSUM-P ( rem -- acc ) 0 2DUP . . CR SWAP TVERRSUM-REC DUP SINGLE-DIGIT IF . CR ELSE CR RECURSE THEN ;
